// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Pomni.Client.GitHub.Models
{
    /// <summary>
    /// The stack information associated with a pull request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class PullRequestStack : IParsable
    {
        /// <summary>The base property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.GitHub.Models.PullRequestStack_base? Base { get; set; }
#nullable restore
#else
        public global::Pomni.Client.GitHub.Models.PullRequestStack_base Base { get; set; }
#endif
        /// <summary>The ID of the stack that this pull request belongs to.</summary>
        public int? Id { get; set; }
        /// <summary>The number of the stack that this pull request belongs to.</summary>
        public int? Number { get; set; }
        /// <summary>The one-based position of this pull request within the stack, where 1 is the bottom of the stack.</summary>
        public int? Position { get; set; }
        /// <summary>The total number of pull requests in the stack.</summary>
        public int? Size { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.GitHub.Models.PullRequestStack"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Pomni.Client.GitHub.Models.PullRequestStack CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Pomni.Client.GitHub.Models.PullRequestStack();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base", n => { Base = n.GetObjectValue<global::Pomni.Client.GitHub.Models.PullRequestStack_base>(global::Pomni.Client.GitHub.Models.PullRequestStack_base.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "number", n => { Number = n.GetIntValue(); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "size", n => { Size = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Pomni.Client.GitHub.Models.PullRequestStack_base>("base", Base);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("number", Number);
            writer.WriteIntValue("position", Position);
            writer.WriteIntValue("size", Size);
        }
    }
}
#pragma warning restore CS0618
