// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Pomni.Client.Codeberg.Repos.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Pomni.Client.Codeberg.Repos
{
    /// <summary>
    /// Builds and executes requests for operations under \repos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class ReposRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Pomni.Client.Codeberg.repos.item collection</summary>
        /// <param name="position">owner of the repo</param>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Repos.Item.WithOwnerItemRequestBuilder"/></returns>
        public global::Pomni.Client.Codeberg.Repos.Item.WithOwnerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("owner", position);
                return new global::Pomni.Client.Codeberg.Repos.Item.WithOwnerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.ReposRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReposRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.ReposRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReposRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
