// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Pomni.Client.Codeberg.Models;
using Pomni.Client.Codeberg.Repos.Item.Item.Branches;
using Pomni.Client.Codeberg.Repos.Item.Item.Git;
using Pomni.Client.Codeberg.Repos.Item.Item.Pulls;
using Pomni.Client.Codeberg.Repos.Item.Item.Releases;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Pomni.Client.Codeberg.Repos.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class WithRepoItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The branches property</summary>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.Branches.BranchesRequestBuilder Branches
        {
            get => new global::Pomni.Client.Codeberg.Repos.Item.Item.Branches.BranchesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The git property</summary>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.Git.GitRequestBuilder Git
        {
            get => new global::Pomni.Client.Codeberg.Repos.Item.Item.Git.GitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pulls property</summary>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.Pulls.PullsRequestBuilder Pulls
        {
            get => new global::Pomni.Client.Codeberg.Repos.Item.Item.Pulls.PullsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The releases property</summary>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.Releases.ReleasesRequestBuilder Releases
        {
            get => new global::Pomni.Client.Codeberg.Repos.Item.Item.Releases.ReleasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.WithRepoItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRepoItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.WithRepoItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRepoItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}", rawUrl)
        {
        }
        /// <summary>
        /// Get a repository
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Models.Repository"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Pomni.Client.Codeberg.Models.APINotFound">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Pomni.Client.Codeberg.Models.Repository?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Pomni.Client.Codeberg.Models.Repository> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Pomni.Client.Codeberg.Models.APINotFound.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Pomni.Client.Codeberg.Models.Repository>(requestInfo, global::Pomni.Client.Codeberg.Models.Repository.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a repository
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.WithRepoItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.WithRepoItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Pomni.Client.Codeberg.Repos.Item.Item.WithRepoItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
