// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Pomni.Client.Codeberg.Models
{
    /// <summary>
    /// PayloadCommit represents a commit
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class PayloadCommit : IParsable
    {
        /// <summary>The added property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Added { get; set; }
#nullable restore
#else
        public List<string> Added { get; set; }
#endif
        /// <summary>PayloadUser represents the author or committer of a commit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.Codeberg.Models.PayloadUser? Author { get; set; }
#nullable restore
#else
        public global::Pomni.Client.Codeberg.Models.PayloadUser Author { get; set; }
#endif
        /// <summary>PayloadUser represents the author or committer of a commit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.Codeberg.Models.PayloadUser? Committer { get; set; }
#nullable restore
#else
        public global::Pomni.Client.Codeberg.Models.PayloadUser Committer { get; set; }
#endif
        /// <summary>sha1 hash of the commit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Modified { get; set; }
#nullable restore
#else
        public List<string> Modified { get; set; }
#endif
        /// <summary>The removed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Removed { get; set; }
#nullable restore
#else
        public List<string> Removed { get; set; }
#endif
        /// <summary>The timestamp property</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>PayloadCommitVerification represents the GPG verification of a commit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.Codeberg.Models.PayloadCommitVerification? Verification { get; set; }
#nullable restore
#else
        public global::Pomni.Client.Codeberg.Models.PayloadCommitVerification Verification { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Models.PayloadCommit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Pomni.Client.Codeberg.Models.PayloadCommit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Pomni.Client.Codeberg.Models.PayloadCommit();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "added", n => { Added = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "author", n => { Author = n.GetObjectValue<global::Pomni.Client.Codeberg.Models.PayloadUser>(global::Pomni.Client.Codeberg.Models.PayloadUser.CreateFromDiscriminatorValue); } },
                { "committer", n => { Committer = n.GetObjectValue<global::Pomni.Client.Codeberg.Models.PayloadUser>(global::Pomni.Client.Codeberg.Models.PayloadUser.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "modified", n => { Modified = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "removed", n => { Removed = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "verification", n => { Verification = n.GetObjectValue<global::Pomni.Client.Codeberg.Models.PayloadCommitVerification>(global::Pomni.Client.Codeberg.Models.PayloadCommitVerification.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("added", Added);
            writer.WriteObjectValue<global::Pomni.Client.Codeberg.Models.PayloadUser>("author", Author);
            writer.WriteObjectValue<global::Pomni.Client.Codeberg.Models.PayloadUser>("committer", Committer);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("message", Message);
            writer.WriteCollectionOfPrimitiveValues<string>("modified", Modified);
            writer.WriteCollectionOfPrimitiveValues<string>("removed", Removed);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteStringValue("url", Url);
            writer.WriteObjectValue<global::Pomni.Client.Codeberg.Models.PayloadCommitVerification>("verification", Verification);
        }
    }
}
#pragma warning restore CS0618
