// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Pomni.Client.Codeberg.Models
{
    /// <summary>
    /// PRBranchInfo information about a branch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class PRBranchInfo : IParsable
    {
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ref { get; set; }
#nullable restore
#else
        public string Ref { get; set; }
#endif
        /// <summary>Repository represents a repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.Codeberg.Models.Repository? Repo { get; set; }
#nullable restore
#else
        public global::Pomni.Client.Codeberg.Models.Repository Repo { get; set; }
#endif
        /// <summary>The repo_id property</summary>
        public long? RepoId { get; set; }
        /// <summary>The sha property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sha { get; set; }
#nullable restore
#else
        public string Sha { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Models.PRBranchInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Pomni.Client.Codeberg.Models.PRBranchInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Pomni.Client.Codeberg.Models.PRBranchInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "label", n => { Label = n.GetStringValue(); } },
                { "ref", n => { Ref = n.GetStringValue(); } },
                { "repo", n => { Repo = n.GetObjectValue<global::Pomni.Client.Codeberg.Models.Repository>(global::Pomni.Client.Codeberg.Models.Repository.CreateFromDiscriminatorValue); } },
                { "repo_id", n => { RepoId = n.GetLongValue(); } },
                { "sha", n => { Sha = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("ref", Ref);
            writer.WriteObjectValue<global::Pomni.Client.Codeberg.Models.Repository>("repo", Repo);
            writer.WriteLongValue("repo_id", RepoId);
            writer.WriteStringValue("sha", Sha);
        }
    }
}
#pragma warning restore CS0618
