// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Pomni.Client.Codeberg.Models
{
    /// <summary>
    /// Release represents a repository release
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class Release : IParsable
    {
        /// <summary>TagArchiveDownloadCount counts how many times a archive was downloaded</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.Codeberg.Models.TagArchiveDownloadCount? ArchiveDownloadCount { get; set; }
#nullable restore
#else
        public global::Pomni.Client.Codeberg.Models.TagArchiveDownloadCount ArchiveDownloadCount { get; set; }
#endif
        /// <summary>The assets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Pomni.Client.Codeberg.Models.Attachment>? Assets { get; set; }
#nullable restore
#else
        public List<global::Pomni.Client.Codeberg.Models.Attachment> Assets { get; set; }
#endif
        /// <summary>User represents a user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.Codeberg.Models.User? Author { get; set; }
#nullable restore
#else
        public global::Pomni.Client.Codeberg.Models.User Author { get; set; }
#endif
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The draft property</summary>
        public bool? Draft { get; set; }
        /// <summary>The hide_archive_links property</summary>
        public bool? HideArchiveLinks { get; set; }
        /// <summary>The html_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HtmlUrl { get; set; }
#nullable restore
#else
        public string HtmlUrl { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The prerelease property</summary>
        public bool? Prerelease { get; set; }
        /// <summary>The published_at property</summary>
        public DateTimeOffset? PublishedAt { get; set; }
        /// <summary>The tag_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TagName { get; set; }
#nullable restore
#else
        public string TagName { get; set; }
#endif
        /// <summary>The tarball_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TarballUrl { get; set; }
#nullable restore
#else
        public string TarballUrl { get; set; }
#endif
        /// <summary>The target_commitish property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetCommitish { get; set; }
#nullable restore
#else
        public string TargetCommitish { get; set; }
#endif
        /// <summary>The upload_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UploadUrl { get; set; }
#nullable restore
#else
        public string UploadUrl { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The zipball_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ZipballUrl { get; set; }
#nullable restore
#else
        public string ZipballUrl { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Models.Release"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Pomni.Client.Codeberg.Models.Release CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Pomni.Client.Codeberg.Models.Release();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archive_download_count", n => { ArchiveDownloadCount = n.GetObjectValue<global::Pomni.Client.Codeberg.Models.TagArchiveDownloadCount>(global::Pomni.Client.Codeberg.Models.TagArchiveDownloadCount.CreateFromDiscriminatorValue); } },
                { "assets", n => { Assets = n.GetCollectionOfObjectValues<global::Pomni.Client.Codeberg.Models.Attachment>(global::Pomni.Client.Codeberg.Models.Attachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "author", n => { Author = n.GetObjectValue<global::Pomni.Client.Codeberg.Models.User>(global::Pomni.Client.Codeberg.Models.User.CreateFromDiscriminatorValue); } },
                { "body", n => { Body = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "draft", n => { Draft = n.GetBoolValue(); } },
                { "hide_archive_links", n => { HideArchiveLinks = n.GetBoolValue(); } },
                { "html_url", n => { HtmlUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "prerelease", n => { Prerelease = n.GetBoolValue(); } },
                { "published_at", n => { PublishedAt = n.GetDateTimeOffsetValue(); } },
                { "tag_name", n => { TagName = n.GetStringValue(); } },
                { "tarball_url", n => { TarballUrl = n.GetStringValue(); } },
                { "target_commitish", n => { TargetCommitish = n.GetStringValue(); } },
                { "upload_url", n => { UploadUrl = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "zipball_url", n => { ZipballUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Pomni.Client.Codeberg.Models.TagArchiveDownloadCount>("archive_download_count", ArchiveDownloadCount);
            writer.WriteCollectionOfObjectValues<global::Pomni.Client.Codeberg.Models.Attachment>("assets", Assets);
            writer.WriteObjectValue<global::Pomni.Client.Codeberg.Models.User>("author", Author);
            writer.WriteStringValue("body", Body);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteBoolValue("draft", Draft);
            writer.WriteBoolValue("hide_archive_links", HideArchiveLinks);
            writer.WriteStringValue("html_url", HtmlUrl);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("prerelease", Prerelease);
            writer.WriteDateTimeOffsetValue("published_at", PublishedAt);
            writer.WriteStringValue("tag_name", TagName);
            writer.WriteStringValue("tarball_url", TarballUrl);
            writer.WriteStringValue("target_commitish", TargetCommitish);
            writer.WriteStringValue("upload_url", UploadUrl);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("zipball_url", ZipballUrl);
        }
    }
}
#pragma warning restore CS0618
