// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Pomni.Client.Codeberg.Models
{
    /// <summary>
    /// RepoTransfer represents a pending repo transfer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class RepoTransfer : IParsable
    {
        /// <summary>User represents a user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.Codeberg.Models.User? Doer { get; set; }
#nullable restore
#else
        public global::Pomni.Client.Codeberg.Models.User Doer { get; set; }
#endif
        /// <summary>User represents a user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Pomni.Client.Codeberg.Models.User? Recipient { get; set; }
#nullable restore
#else
        public global::Pomni.Client.Codeberg.Models.User Recipient { get; set; }
#endif
        /// <summary>The teams property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Pomni.Client.Codeberg.Models.Team>? Teams { get; set; }
#nullable restore
#else
        public List<global::Pomni.Client.Codeberg.Models.Team> Teams { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Models.RepoTransfer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Pomni.Client.Codeberg.Models.RepoTransfer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Pomni.Client.Codeberg.Models.RepoTransfer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "doer", n => { Doer = n.GetObjectValue<global::Pomni.Client.Codeberg.Models.User>(global::Pomni.Client.Codeberg.Models.User.CreateFromDiscriminatorValue); } },
                { "recipient", n => { Recipient = n.GetObjectValue<global::Pomni.Client.Codeberg.Models.User>(global::Pomni.Client.Codeberg.Models.User.CreateFromDiscriminatorValue); } },
                { "teams", n => { Teams = n.GetCollectionOfObjectValues<global::Pomni.Client.Codeberg.Models.Team>(global::Pomni.Client.Codeberg.Models.Team.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Pomni.Client.Codeberg.Models.User>("doer", Doer);
            writer.WriteObjectValue<global::Pomni.Client.Codeberg.Models.User>("recipient", Recipient);
            writer.WriteCollectionOfObjectValues<global::Pomni.Client.Codeberg.Models.Team>("teams", Teams);
        }
    }
}
#pragma warning restore CS0618
