// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Pomni.Client.Codeberg.Repos.Item.Item.Branches.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Pomni.Client.Codeberg.Repos.Item.Item.Branches
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}\branches
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class BranchesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Pomni.Client.Codeberg.repos.item.item.branches.item collection</summary>
        /// <param name="position">branch to get</param>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Branches.Item.WithBranchItemRequestBuilder"/></returns>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.Branches.Item.WithBranchItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("branch", position);
                return new global::Pomni.Client.Codeberg.Repos.Item.Item.Branches.Item.WithBranchItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Branches.BranchesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BranchesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/branches", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Branches.BranchesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BranchesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/branches", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
