// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Pomni.Client.Codeberg.Repos.Item.Item.Releases.Latest;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Pomni.Client.Codeberg.Repos.Item.Item.Releases
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}\releases
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class ReleasesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The latest property</summary>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.Releases.Latest.LatestRequestBuilder Latest
        {
            get => new global::Pomni.Client.Codeberg.Repos.Item.Item.Releases.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Releases.ReleasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleasesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/releases", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Releases.ReleasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleasesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/releases", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
