// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Pomni.Client.Codeberg.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Pomni.Client.Codeberg.Repos.Item.Item.Pulls.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}\pulls\{index}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class WithIndexItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Pulls.Item.WithIndexItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIndexItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/pulls/{index}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Pulls.Item.WithIndexItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIndexItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/pulls/{index}", rawUrl)
        {
        }
        /// <summary>
        /// Update a pull request. If using deadline only the date will be taken into account, and time of day ignored.
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Models.PullRequest"/></returns>
        /// <param name="body">EditPullRequestOption options when modify pull request</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Pomni.Client.Codeberg.Models.APIForbiddenError">When receiving a 403 status code</exception>
        /// <exception cref="global::Pomni.Client.Codeberg.Models.APINotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Pomni.Client.Codeberg.Models.APIError">When receiving a 409 status code</exception>
        /// <exception cref="global::Pomni.Client.Codeberg.Models.APIError">When receiving a 412 status code</exception>
        /// <exception cref="global::Pomni.Client.Codeberg.Models.APIValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Pomni.Client.Codeberg.Models.PullRequest?> PatchAsync(global::Pomni.Client.Codeberg.Models.EditPullRequestOption body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Pomni.Client.Codeberg.Models.PullRequest> PatchAsync(global::Pomni.Client.Codeberg.Models.EditPullRequestOption body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Pomni.Client.Codeberg.Models.APIForbiddenError.CreateFromDiscriminatorValue },
                { "404", global::Pomni.Client.Codeberg.Models.APINotFound.CreateFromDiscriminatorValue },
                { "409", global::Pomni.Client.Codeberg.Models.APIError.CreateFromDiscriminatorValue },
                { "412", global::Pomni.Client.Codeberg.Models.APIError.CreateFromDiscriminatorValue },
                { "422", global::Pomni.Client.Codeberg.Models.APIValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Pomni.Client.Codeberg.Models.PullRequest>(requestInfo, global::Pomni.Client.Codeberg.Models.PullRequest.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a pull request. If using deadline only the date will be taken into account, and time of day ignored.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">EditPullRequestOption options when modify pull request</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Pomni.Client.Codeberg.Models.EditPullRequestOption body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Pomni.Client.Codeberg.Models.EditPullRequestOption body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Pulls.Item.WithIndexItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.Pulls.Item.WithIndexItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Pomni.Client.Codeberg.Repos.Item.Item.Pulls.Item.WithIndexItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
