// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Pomni.Client.Codeberg.Repos.Item.Item.Git.Refs.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Pomni.Client.Codeberg.Repos.Item.Item.Git.Refs
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}\git\refs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class RefsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Pomni.Client.Codeberg.repos.item.item.git.refs.item collection</summary>
        /// <param name="position">part or full name of the ref</param>
        /// <returns>A <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Git.Refs.Item.WithRefItemRequestBuilder"/></returns>
        public global::Pomni.Client.Codeberg.Repos.Item.Item.Git.Refs.Item.WithRefItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("ref", position);
                return new global::Pomni.Client.Codeberg.Repos.Item.Item.Git.Refs.Item.WithRefItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Git.Refs.RefsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RefsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/git/refs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Pomni.Client.Codeberg.Repos.Item.Item.Git.Refs.RefsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RefsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/git/refs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
