name: Pomni

on:
  schedule:
    - cron: "0 12 * * *"
      timezone: Europe/London

  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: canidae-solutions/lix-quick-install-action@v4

      - uses: cachix/cachix-action@v17
        with:
          name: drakon64
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: nix-shell -A pomni --run "exit"

      - run: |
          nix-shell -A pomni --run "pomni modify nixpkgs --branch master"
          nix-shell -A pomni --run "pomni bot github"
        env:
          BEARER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
